### ISSUE TITLE
Damage

### ISSUE THREAD

**Issue by servantthought** [SalmonDE/EnderPearl#1]
What is the benefit of an ender pearl plugin?

**Comment by servantthought** [comment]
Never mind I figured out

DelayedEffectsTask.php

$this->player->attack($event = new EntityDamageEvent($this->player, EntityDamageEvent::CAUSE_FALL, 5));

Changed
EntityDamageEvent::CAUSE_FALL, 0

**Comment by SalmonDE** [comment]
Ender pearls were not implemented into pmmp prior to cc1a3d695f7deb223c9084c5af857d0f2b212dda.
The "benefit" of this plugin was to provide a basic implementation for them so they would just serve their purpose.
